// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct connection: they issue statements a connection
    // pooler in transaction mode cannot carry. DATABASE_URL points at the
    // pooled endpoint for the running app, so prefer DIRECT_URL when present.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
